name = "example"

command = "git"
args = ["clone", "https://github.com/rust-lang/rust.git"]

[hosts]
[hosts.rogue1]
command = "echo"
args = ["running local setup for rogue1"]

[hosts.rogue2]
command = "echo"
args = ["running local setup for rogue2"]

[hosts.rogue3]
command = "echo"
args = ["running local setup for rogue3"]

[hosts.rogue4]
command = "echo"
args = ["running local setup for rogue4"]

[hosts.rogue5]
command = "echo"
args = ["running local setup for rogue5"]

[hosts.rogue6]
command = "echo"
args = ["running local setup for rogue6"]

[hosts.arch]
command = "./rust/x.py"
args = ["build"]
