name = "example"

setup = [
  "echo 'running global setup'"
]

[hosts]
[hosts.rogue1]
setup = [
  "echo 'running local setup for rogue1'",
]

[hosts.rogue2]
setup = [
  "echo 'running local setup for rogue2'",
]

[hosts.rogue3]
setup = [
  "echo 'running local setup for rogue3'",
]

[hosts.rogue4]
setup = [
  "echo 'running local setup for rogue4'",
]

[hosts.rogue5]
setup = [
  "echo 'running local setup for rogue5'",
]

[hosts.rogue6]
setup = [
  "echo 'running local setup for rogue6'",
]
