name = "example"

command = "git"
args = ["clone", "https://github.com/rust-lang/rust.git"]

[hosts]
[hosts.rogue1]
command = "./loop.sh"
args = ["looping from rogue1"]

[hosts.rogue2]
command = "./loop.sh"
args = ["looping from rogue2"]

[hosts.rogue3]
command = "./loop.sh"
args = ["looping from rogue3"]

[hosts.rogue4]
command = "./loop.sh"
args = ["looping from rogue4"]

[hosts.rogue5]
command = "./loop.sh"
args = ["looping from rogue5"]

[hosts.rogue6]
command = "./loop.sh"
args = ["looping from rogue6"]

[hosts.arch]
command = "./rust/x.py"
args = ["build"]
